from typing import Any, List, TypeVar, Generic, Tuple

class dtype: ...
class uint8(dtype): ...
class float32(dtype): ...

class ndarray:
    shape: Tuple[int, ...]
    size: int
    def tobytes(self) -> bytes: ...
    def astype(self, t: Any) -> 'ndarray': ...
    def __getitem__(self, item: Any) -> Any: ...
    def flatten(self) -> 'ndarray': ...
    def reshape(self, *args: Any) -> 'ndarray': ...
    def mean(self, axis: Any = None) -> Any: ...
    def ptp(self, axis: Any = None) -> Any: ...
    def clip(self, min: Any, max: Any) -> 'ndarray': ...
    def copy(self) -> 'ndarray': ...
    
    # Operators
    def __gt__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __add__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...

def frombuffer(buffer: Any, dtype: Any) -> ndarray: ...
def array(object: Any, dtype: Any = ...) -> ndarray: ...
def zeros(shape: Any, dtype: Any = ...) -> ndarray: ...
def mean(a: Any, axis: Any = None) -> Any: ...
def ptp(a: Any, axis: Any = None) -> Any: ...
def clip(a: Any, a_min: Any, a_max: Any) -> Any: ...
def where(condition: Any, x: Any = None, y: Any = None) -> Any: ...