from typing import Any, Optional, Dict, List, Union, AsyncIterator, Callable

class Response:
    status_code: int
    headers: dict[str, str]
    content: bytes
    text: str
    def json(self, **kwargs: Any) -> Any: ...
    def raise_for_status(self) -> None: ...
    async def aread(self) -> bytes: ...
    def close(self) -> None: ...
    async def aclose(self) -> None: ...
    async def aiter_bytes(self, chunk_size: Optional[int] = None) -> AsyncIterator[bytes]: ...

class AsyncClient:
    def __init__(self, *, base_url: str = "", timeout: Any = None, limits: Any = None, **kwargs: Any) -> None: ...
    async def get(self, url: str, **kwargs: Any) -> Response: ...
    async def post(self, url: str, **kwargs: Any) -> Response: ...
    async def put(self, url: str, **kwargs: Any) -> Response: ...
    async def delete(self, url: str, **kwargs: Any) -> Response: ...
    async def request(self, method: str, url: str, **kwargs: Any) -> Response: ...
    def stream(self, method: str, url: str, **kwargs: Any) -> Any: ...
    async def aclose(self) -> None: ...
    async def __aenter__(self) -> 'AsyncClient': ...
    async def __aexit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...

class RequestError(Exception): ...
class HTTPStatusError(Exception): ...
class TimeoutException(Exception): ...
class NetworkError(Exception): ...

class Limits:
    def __init__(self, max_keepalive_connections: Optional[int] = None, max_connections: Optional[int] = None) -> None: ...

class Timeout:
    def __init__(self, timeout: Union[float, None] = None, connect: Union[float, None] = None, read: Union[float, None] = None, write: Union[float, None] = None, pool: Union[float, None] = None) -> None: ...