from typing import Any, Callable, Coroutine

def run(app: Any, **kwargs: Any) -> None: ...

class Config:
    def __init__(self, app: Any, **kwargs: Any) -> None: ...

class Server:
    def __init__(self, config: Config) -> None: ...
    async def serve(self, sockets: Any = None) -> None: ...
