from typing import Any, Callable, Type, List, Optional, TypeVar, Coroutine, Union, Dict

_T = TypeVar("_T")

class HTTPException(Exception):
    status_code: int
    detail: Any
    def __init__(self, status_code: int, detail: Any = None, headers: Optional[Dict[str, Any]] = None) -> None: ...

class Request:
    method: str
    url: Any
    headers: Dict[str, str]
    path_params: Dict[str, Any]
    query_params: Dict[str, Any]
    client: Any
    cookies: Dict[str, str]
    def body(self) -> Coroutine[Any, Any, bytes]: ...
    def json(self) -> Coroutine[Any, Any, Any]: ...
    async def is_disconnected(self) -> bool: ...

class Response:
    status_code: int
    def __init__(self, content: Any = None, status_code: int = 200, headers: Optional[Dict[str, str]] = None, media_type: Optional[str] = None, background: Any = None) -> None: ...

class FastAPI:
    state: Any
    def __init__(self, **kwargs: Any) -> None: ...
    def mount(self, path: str, app: Any, name: Optional[str] = None) -> None: ...
    def add_middleware(self, middleware_class: type, **options: Any) -> None: ...
    def include_router(self, router: Any, **kwargs: Any) -> None: ...
    
    # Decorators
    def get(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def post(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def put(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def delete(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def patch(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def on_event(self, event_type: str) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class APIRouter:
    def get(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def post(self, path: str, **kwargs: Any) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...

class UploadFile:
    filename: str
    content_type: str
    file: Any
    async def read(self, size: int = -1) -> bytes: ...
    async def write(self, data: bytes) -> None: ...
    async def seek(self, offset: int) -> None: ...
    async def close(self) -> None: ...

def Depends(dependency: Optional[Callable[..., Any]] = None, *, use_cache: bool = True) -> Any: ...
def status() -> Any: ...

class BackgroundTasks:
    def add_task(self, func: Callable[..., Any], *args: Any, **kwargs: Any) -> None: ...