from typing import Any, Tuple, Optional
from numpy import ndarray

IMREAD_COLOR: int
IMWRITE_JPEG_QUALITY: int

def imencode(ext: str, img: Any, params: Any = ...) -> Tuple[bool, ndarray]: ...
def imdecode(buf: Any, flags: int) -> Optional[ndarray]: ...
def resize(src: Any, dsize: Any, interpolation: int = ...) -> Any: ...
def cvtColor(src: Any, code: int) -> Any: ...

COLOR_BGR2GRAY: int
COLOR_BGRA2BGR: int
INTER_AREA: int
TM_SQDIFF_NORMED: int
def matchTemplate(image: Any, templ: Any, method: int) -> Any: ...
def minMaxLoc(src: Any) -> Tuple[float, float, Any, Any]: ...
def GaussianBlur(src: Any, ksize: Any, sigmaX: float) -> Any: ...
