from typing import Any, Optional, Dict

class Response:
    def __init__(self, content: Any = None, status_code: int = 200, headers: Optional[Dict[str, str]] = None, media_type: Optional[str] = None, background: Any = None) -> None: ...

class FileResponse:
    def __init__(self, path: str, status_code: int = 200, headers: Optional[Dict[str, str]] = None, media_type: Optional[str] = None, background: Any = None, filename: Optional[str] = None, stat_result: Optional[Any] = None, method: Optional[str] = None, content_disposition_type: str = "attachment") -> None: ...

class JSONResponse:
    def __init__(self, content: Any, status_code: int = 200, headers: Optional[Dict[str, str]] = None, media_type: Optional[str] = None, background: Any = None) -> None: ...

class StreamingResponse:
    def __init__(self, content: Any, status_code: int = 200, headers: Optional[Dict[str, str]] = None, media_type: Optional[str] = None, background: Any = None) -> None: ...

class PlainTextResponse(Response): ...
class HTMLResponse(Response): ...